variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: cimpy

stages:
- prepare
- test
- generate
- deploy


docker:
    stage: prepare
    script:
        - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    tags:
        - shell
        - linux


test:
    stage: test
    script:
        - pytest
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker
