variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: cimpy

stages:
- prepare
- test
- generate
- deploy


docker:
    stage: prepare
    script:
        - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    tags:
        - shell
        - linux


unit-test:
    stage: test
    script:
        - pytest -v -cov
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker

format:
    stage: lint
    allow_failure: true
    script:
        - flake8 --statistics
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker
