variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: cimpy

stages:
- prepare
- test


build-image:
    stage: prepare
    image: docker:20.10
    script:
        - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    tags:
        - docker


test-cimadapter:
    stage: test
    script:
        - pytest -v -cov --junitxml=report.xml test/test_network_models_controller.py
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker
    artifacts:
        reports:
            junit: report.xml


format:
    stage: test
    allow_failure: true
    script:
        - flake8 --statistics
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker
