version: "3.8"
services:
  web:
    depends_on:
      - redis
    image: "cimpy-server"
    ports:
      - "8080:8080"
    networks:
      cimpy-server:
        aliases:
          - "redis"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      cimpy-server:
        aliases:
          - "redis"

networks:
  cimpy-server:
